package sbs1

const (
	// MessageTypeSelectionChange is am message generated when the user changes the selected aircraft in
	// BaseStation.
	MessageTypeSelectionChange = "SEL"

	// MessageTypeNewId is a message generated when an aircraft being tracked sets or changes its
	// callsign.
	MessageTypeNewID = "ID"

	// MessageTypeNewAircraft is a message generated when the SBS picks up a signal for an aircraft that it
	// isn't currently tracking.
	MessageTypeNewAircraft = "AIR"

	// MessageTypeStatusChange is a message generated when an aircraft's status changes according to the
	// time-out values in the SBS1 Data Settings menu.
	MessageTypeStatusChange = "STA"

	// MessageTypeClick is a message generated when the user double-clicks (or presses return) on an
	// aircraft (i.e. to bring up the aircraft details window).
	MessageTypeClick = "CLK"

	// MessageTypeTransmission is a message generated by the aircraft. There are eight different MSG
	// transmission types, see `TransmissionType`.
	MessageTypeTransmission = "MSG"

	// TransmissionTypeESIdentAndCategory is a "ES identification and category", spec "DF17 BDS 0,8" transmission
	TransmissionTypeESIdentAndCategory = 1

	// TransmissionTypeESSurfacePosition is a "ES surface position message", spec "DF17 BDS 0,6" transmission
	TransmissionTypeESSurfacePosition = 2

	TransmissionTypeESAirbornPosition = 3
)
