package sbs1

import "time"

const (
	// MessageTypeSelectionChange is am message generated when the user changes the selected aircraft in
	// BaseStation.
	MessageTypeSelectionChange = "SEL"

	// MessageTypeNewID is a message generated when an aircraft being tracked sets or changes its
	// callsign.
	MessageTypeNewID = "ID"

	// MessageTypeNewAircraft is a message generated when the SBS picks up a signal for an aircraft that it
	// isn't currently tracking.
	MessageTypeNewAircraft = "AIR"

	// MessageTypeStatusChange is a message generated when an aircraft's status changes according to the
	// time-out values in the SBS1 Data Settings menu.
	MessageTypeStatusChange = "STA"

	// MessageTypeClick is a message generated when the user double-clicks (or presses return) on an
	// aircraft (i.e. to bring up the aircraft details window).
	MessageTypeClick = "CLK"

	// MessageTypeTransmission is a message generated by the aircraft. There are eight different MSG
	// transmission types, see `TransmissionType`.
	MessageTypeTransmission = "MSG"

	// TransmissionTypeESIdentAndCategory is a "ES identification and category", spec "DF17 BDS 0,8" transmission
	TransmissionTypeESIdentAndCategory = 1

	// TransmissionTypeESSurfacePosition is a "ES surface position message", spec "DF17 BDS 0,6" transmission
	TransmissionTypeESSurfacePosition = 2

	// TransmissionTypeESAirbornPosition is a "ES airborne position message", spec "DF17 BDS 0,5" transmission
	TransmissionTypeESAirbornPosition = 3

	// TransmissionTypeESAirbornVelocity is a "ES airborne velocity message", spec "DF17 BDS 0,9" transmission
	TransmissionTypeESAirbornVelocity = 4

	// TransmissionTypeSurveillanceAlt is a "Surveillance alt message", spec "DF4, DF20" transmission
	TransmissionTypeSurveillanceAlt = 5

	// TransmissionTypeSurveillanceID is a "Surveillance ID message", spec "DF5, DF21" transmission
	TransmissionTypeSurveillanceID = 6

	// TransmissionTypeAirToAir is a  "Air-to-air message", spec "DF16" transmission
	TransmissionTypeAirToAir = 7

	// TransmissionTypeAllCallReply is a "All call reply", spec "DF11"
	TransmissionTypeAllCallReply = 8
)

type SBS1Message struct {
	MessageType   string
	AircraftID    int
	HexIdent      int64
	FlightID      string
	GeneratedTime time.Time
	LoggedTime    time.Time
	CallSign      string
	Altitude      int
	GroundSpeed   int
	Track         string
	Latitude      float32
	Longitude     float32
	VerticalRate  int
	Squeak        string
	Alert         string
	Emergency     string
	SPI           string
	IsOnGround    bool
}

func sbsToBool(val string) bool {
	if val != "0" {
		return true
	} else {
		return false
	}
}
